#!/bin/bash

# showing help
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "$(basename "$0") [-h] -- Runs the installation:
    -h/--help       show this help text
    --production    installs as production release (under UPIPE_ROOT). Otherwise, if not supplied installs under UPIPE_DEV_ROOT (default)"
  exit 0
fi

# production release
if [[ $* == *--production* ]]; then
  # removing any previous build folder
  if [ -d "build_release" ]; then
    rm -r "build_release"
  fi

  # making sure UPIPE_ROOT is defined
  if [ -z $UPIPE_ROOT ]; then
    echo "UPIPE_ROOT is not defined"
    exit 1
  fi

  # showing a prompt confirmation, in case of a mistake
  read -r -p "Are you sure you want to run the production release? [y/N] " response
  if [[ "$response" =~ ^(yes|y)$ ]]; then
    # running installation
    qbs build_release project.releaseType:production qbs.installRoot:$UPIPE_ROOT
  fi

# development release
else

  # making sure UPIPE_DEV_ROOT is defined
  if [ -z $UPIPE_DEV_ROOT ]; then
    echo "UPIPE_DEV_ROOT is not defined"
    exit 1
  fi

  # TODO: workaround to avoid the installation not detecting
  # modifications in files and installing a wrong version from the cache
  # (rather than invalidating the cache).
  # This issue has been noticed in qbs 1.8.1
  if [ -d "default" ]; then
    rm -r "default"
  fi

  # ATTENTION:
  # The development version is based on the current UVER_UPYTHON_VERSION, in case
  # you want to build to all python versions, run the line bellow:
  # bash -c "unset UVER_UPYTHON_VERSION; ./install"
  pythonMajorVersion=$(majorver $UVER_UPYTHON_VERSION)

  # running installation
  qbs project.releaseType:dev project.pythonMajorVersion:$pythonMajorVersion qbs.installRoot:$UPIPE_DEV_ROOT

fi
